// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPJbayKRKhWa8PIhc4zqyohtrexRQz50I',
    appId: '1:575500261467:web:95884cc5ca0915076c477e',
    messagingSenderId: '575500261467',
    projectId: 'portfolio-9ca66',
    authDomain: 'portfolio-9ca66.firebaseapp.com',
    storageBucket: 'portfolio-9ca66.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlAj_vvjccJ9li0AfVfXBDbL5suPXhh74',
    appId: '1:575500261467:android:6389c585bb5fea7e6c477e',
    messagingSenderId: '575500261467',
    projectId: 'portfolio-9ca66',
    storageBucket: 'portfolio-9ca66.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-zPllkAh74afnDCXA5kLKl_-zinvImhY',
    appId: '1:575500261467:ios:08901a4ba8dd06cc6c477e',
    messagingSenderId: '575500261467',
    projectId: 'portfolio-9ca66',
    storageBucket: 'portfolio-9ca66.appspot.com',
    iosClientId: '575500261467-vp5aiiid49e43fmim3allscmktn7v3qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.portfolio',
  );
}
